### ISSUE TITLE
horisontal_bar_plot()

### ISSUE THREAD

**Issue by soppen** [swehip/slrplotfun#20]
`horisontal_bar_plot()` är ganska slafsigt ihoptejpad för ett specifikt ändamål och saknar mycket av den funktionalitet som `bar_plot()` har. Det bästa vore, tycker jag, om det gick att slå ihop `bar_plot()` och `horisontal_bar_plot()` till en och samma funktion. 

Det finns som val att lägga på `coord_flip()` till `bar_plot()` med `flip = TRUE` men detta val hanterar inte label till höger i figuren. Det borde inte vara ett jättestort jobb att flytta `horisontal_bar_plot()` till if-satsen på [rad 286 i bar_plot.R](https://github.com/swehip/slrplotfun/blob/8912bf3b10b2645a2136eaf2cdfdcdabd8cefdb9/R/bar_plot.R#L286)

**Comment by eribul** [comment]
Denna issue har kopierats över till: https://gitlab.com/registercentrum/statistikenheten/slrplotfun/-/issues/17
inför att detta repo arkiveras
